//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/7_InputAction/PlayerSkillInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerSkillInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerSkillInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerSkillInput"",
    ""maps"": [
        {
            ""name"": ""CommandKey"",
            ""id"": ""bb8e83a0-6469-4056-9206-08fe77fbe035"",
            ""actions"": [
                {
                    ""name"": ""s"",
                    ""type"": ""Button"",
                    ""id"": ""a61ebc6e-8688-47b3-abe0-ed8c4d4ee8de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""f"",
                    ""type"": ""Button"",
                    ""id"": ""fbe240b9-82c8-449b-bb07-2c2a650273f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""e"",
                    ""type"": ""Button"",
                    ""id"": ""3b625304-4bb7-4970-a47c-4d44055169fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""q"",
                    ""type"": ""Button"",
                    ""id"": ""1d30eb58-c436-40f6-b994-9ab6bd0b2021"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""lShift"",
                    ""type"": ""Button"",
                    ""id"": ""45f98571-ee86-4590-b5b4-e0b8954db46f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouseLeft"",
                    ""type"": ""Button"",
                    ""id"": ""72df718a-916c-47b6-8d6f-e98455311b0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouseRight"",
                    ""type"": ""Button"",
                    ""id"": ""fa429467-d20e-4e46-9651-2ea62d96b75d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc806693-b4a1-4aec-914b-4d85b7d3a4fb"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""f"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""987ecbaf-c3b4-4267-a802-32f9cbd55060"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""e"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f9e2538-253c-4f4a-b7d0-294d7d255e73"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64c50fb5-f85f-4292-b5c3-f57d1eb020c6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17fabe84-85b4-4f7c-91e1-b690afbc40a3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e420b665-7167-4c41-acc5-e2a1d2b39c39"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""s"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc455bf5-5a29-496c-8c20-96e60b666d37"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // CommandKey
        m_CommandKey = asset.FindActionMap("CommandKey", throwIfNotFound: true);
        m_CommandKey_s = m_CommandKey.FindAction("s", throwIfNotFound: true);
        m_CommandKey_f = m_CommandKey.FindAction("f", throwIfNotFound: true);
        m_CommandKey_e = m_CommandKey.FindAction("e", throwIfNotFound: true);
        m_CommandKey_q = m_CommandKey.FindAction("q", throwIfNotFound: true);
        m_CommandKey_lShift = m_CommandKey.FindAction("lShift", throwIfNotFound: true);
        m_CommandKey_mouseLeft = m_CommandKey.FindAction("mouseLeft", throwIfNotFound: true);
        m_CommandKey_mouseRight = m_CommandKey.FindAction("mouseRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CommandKey
    private readonly InputActionMap m_CommandKey;
    private ICommandKeyActions m_CommandKeyActionsCallbackInterface;
    private readonly InputAction m_CommandKey_s;
    private readonly InputAction m_CommandKey_f;
    private readonly InputAction m_CommandKey_e;
    private readonly InputAction m_CommandKey_q;
    private readonly InputAction m_CommandKey_lShift;
    private readonly InputAction m_CommandKey_mouseLeft;
    private readonly InputAction m_CommandKey_mouseRight;
    public struct CommandKeyActions
    {
        private @PlayerSkillInput m_Wrapper;
        public CommandKeyActions(@PlayerSkillInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @s => m_Wrapper.m_CommandKey_s;
        public InputAction @f => m_Wrapper.m_CommandKey_f;
        public InputAction @e => m_Wrapper.m_CommandKey_e;
        public InputAction @q => m_Wrapper.m_CommandKey_q;
        public InputAction @lShift => m_Wrapper.m_CommandKey_lShift;
        public InputAction @mouseLeft => m_Wrapper.m_CommandKey_mouseLeft;
        public InputAction @mouseRight => m_Wrapper.m_CommandKey_mouseRight;
        public InputActionMap Get() { return m_Wrapper.m_CommandKey; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CommandKeyActions set) { return set.Get(); }
        public void SetCallbacks(ICommandKeyActions instance)
        {
            if (m_Wrapper.m_CommandKeyActionsCallbackInterface != null)
            {
                @s.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnS;
                @s.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnS;
                @s.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnS;
                @f.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnF;
                @f.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnF;
                @f.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnF;
                @e.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnE;
                @e.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnE;
                @e.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnE;
                @q.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnQ;
                @q.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnQ;
                @q.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnQ;
                @lShift.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnLShift;
                @lShift.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnLShift;
                @lShift.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnLShift;
                @mouseLeft.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnMouseLeft;
                @mouseLeft.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnMouseLeft;
                @mouseLeft.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnMouseLeft;
                @mouseRight.started -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnMouseRight;
                @mouseRight.performed -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnMouseRight;
                @mouseRight.canceled -= m_Wrapper.m_CommandKeyActionsCallbackInterface.OnMouseRight;
            }
            m_Wrapper.m_CommandKeyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @s.started += instance.OnS;
                @s.performed += instance.OnS;
                @s.canceled += instance.OnS;
                @f.started += instance.OnF;
                @f.performed += instance.OnF;
                @f.canceled += instance.OnF;
                @e.started += instance.OnE;
                @e.performed += instance.OnE;
                @e.canceled += instance.OnE;
                @q.started += instance.OnQ;
                @q.performed += instance.OnQ;
                @q.canceled += instance.OnQ;
                @lShift.started += instance.OnLShift;
                @lShift.performed += instance.OnLShift;
                @lShift.canceled += instance.OnLShift;
                @mouseLeft.started += instance.OnMouseLeft;
                @mouseLeft.performed += instance.OnMouseLeft;
                @mouseLeft.canceled += instance.OnMouseLeft;
                @mouseRight.started += instance.OnMouseRight;
                @mouseRight.performed += instance.OnMouseRight;
                @mouseRight.canceled += instance.OnMouseRight;
            }
        }
    }
    public CommandKeyActions @CommandKey => new CommandKeyActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface ICommandKeyActions
    {
        void OnS(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnE(InputAction.CallbackContext context);
        void OnQ(InputAction.CallbackContext context);
        void OnLShift(InputAction.CallbackContext context);
        void OnMouseLeft(InputAction.CallbackContext context);
        void OnMouseRight(InputAction.CallbackContext context);
    }
}
